title: ENGL 340 Spring 2025
description: ENGL 340 Spring 2025 at SUNY Geneseo
theme: just-the-docs

url: https://paulschacht.net/engl340

# aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# silence deprecation warnings
sass:
    quiet_deps: true # https://github.com/just-the-docs/just-the-docs/issues/1541
    silence_deprecations: ['import'] # https://github.com/just-the-docs/just-the-docs/issues/1607

favicon_ico: "/assets/favicon.ico"
color_scheme: custom
callouts:
  warning:
    title: Be Careful
    color: red
  tip:
    title: Tip
    color: green
  alt-warning:
    color: red
  important:
    title: Important
    color: yellow
  note:
    title: Note
    color: yellow